<!DOCTYPE html>
<!--
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title><?php echo $cedente; ?></title>
    <style type="text/css">
        /* Embed the CSS content here */
        <?php include $resource_path . '/css/styles.css' ?>
    </style>
</head>
<body>

    <div style="width: 666px">
        <div class="noprint info">
            <h2>Instruções de Impressão</h2>
            <ul>
                <li>Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (Não use modo econômico).</li>
                <li>Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens mínimas à esquerda e à direita do formulário.</li>
                <li>Corte na linha indicada. Não rasure, risque, fure ou dobre a região onde se encontra o código de barras.</li>
                <li>Caso não apareça o código de barras no final, pressione F5 para atualizar esta tela.</li>
                <li>Caso tenha problemas ao imprimir, copie a sequencia numérica abaixo e pague no caixa eletrônico ou no internet banking:</li>
            </ul>
            <span class="header">Linha Digitável: <?php echo $linha_digitavel; ?></span>
            <?php if ($valor_documento) : ?><span class="header">Valor: R$ <?php echo $valor_documento; ?></span><?php endif ?>
            <?php if ($pagamento_minimo) : ?><span class="header">Pagamento mínimo: R$ <?php echo $pagamento_minimo; ?></span><?php endif ?>
            <br>
            <div class="linha-pontilhada" style="margin-bottom: 20px;">Recibo do sacado</div>
        </div>

        <div class="info-empresa">
            <?php if ($logotipo) : ?>
            <div style="display: inline-block;">
                <img alt="logotipo" src="<?php echo $logotipo; ?>" />
            </div>
            <?php endif ?>
            <div style="display: inline-block; vertical-align: super;">
                <div><strong><?php echo $cedente; ?></strong></div>
                <div><?php echo $cedente_cpf_cnpj; ?></div>
                <div><?php echo $cedente_endereco1; ?></div>
                <div><?php echo $cedente_endereco2; ?></div>
            </div>

            <div style="display: inline-block;vertical-align: super;float: right;margin-top: 10px;margin-right: 50px;">
                <div style="max-width: 300px;"><strong><?php echo $demonstrativo[0]; ?></strong></div>
                <div style="max-width: 300px;"><?php echo $demonstrativo[1]; ?></div>
                <div style="max-width: 300px;"><?php echo $demonstrativo[2]; ?></div>
                <div style="max-width: 300px;"><?php echo $demonstrativo[3]; ?></div>
                <div style="max-width: 300px;"><?php echo $demonstrativo[4]; ?></div>
            </div>
        </div>
        <br>

        <table class="table-boleto" cellpadding="0" cellspacing="0" border="0">
            <tbody>
                <tr>
                    <td valign="bottom" colspan="8" class="noborder nopadding">
                        <div class="logocontainer">
                            <div class="logobanco">
                                <img src="<?php echo $logo_banco; ?>" alt="logotipo do banco">
                            </div>
                            <div class="codbanco"><?php echo $codigo_banco_com_dv ?></div>
                        </div>
                        <div class="linha-digitavel"><?php echo $linha_digitavel ?></div>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <div class="titulo">Beneficiário</div>
                        <div class="conteudo"><?php echo $cedente ?></div>
                    </td>
                    <td>
                        <div class="titulo">CPF/CNPJ</div>
                        <div class="conteudo"><?php echo $cedente_cpf_cnpj ?></div>
                    </td>
                    <td colspan="2">
                        <div class="titulo">Sacador Avalista</div>
                        <div class="conteudo"><?php echo $sacador_avalista; ?></div>
                    </td>
                    <td>
                        <div class="titulo">Vencimento</div>
                        <div class="conteudo rtl"><?php echo $data_vencimento ?></div>
                    </td>
                </tr>
                <tr>
                    <td colspan="7">
                        <div class="titulo">Endereço Beneficiário/Sacador Avalista</div>
                        <div class="conteudo"><?php echo $sacado_endereco1.' '.$sacado_endereco2 ?></div>
                    </td>
                </tr>
                <tr>
                    <td width="120">
                        <?php if ($mostrar_carteira): ?>
                            <div class="titulo">Carteira / Nosso número</div>
                            <div align="center" class="conteudo"><?php echo $nosso_numero ?></div>
                        <?php else: ?>
                            <div class="titulo">Nosso número</div>
                            <div align="center" class="conteudo"><?php echo $nosso_numero ?></div>
                        <?php endif; ?>
                    </td>
                    <td>
                        <div class="titulo">Carteira</div>
                        <div class="conteudo"><?php echo $carteira ?></div>
                    </td>
                    <td>
                        <div class="titulo">Espécie</div>
                        <div class="conteudo"><?php echo $especie ?></div>
                    </td>
                    <td>
                        <div class="titulo">Quantidade</div>
                        <div class="conteudo rtl"><?php echo $quantidade ?></div>
                    </td>
                    <td>
                        <div class="titulo">Valor</div>
                        <div class="conteudo rtl"><?php echo $valor_unitario ?></div>
                    </td>
                    <td colspan="2">
                        <div class="titulo">Agência/Codigo do Beneficiário</div>
                        <div class="conteudo"><?php echo $agencia_codigo_cedente ?></div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="titulo">Data do documento</div>
                        <div align="center" class="conteudo"><?php echo $data_documento ?></div>
                    </td>
                    <td>
                        <div class="titulo">Número do documento</div>
                        <div class="conteudo lft"><?php echo $numero_documento ?></div>
                    </td>
                    <td colspan="2">
                        <div class="titulo">Espécie do Documento</div>
                        <div class="conteudo"><?php echo $especie_doc ?></div>
                    </td>
                    <td>
                        <div class="titulo">Aceite</div>
                        <div class="conteudo"><?php echo $aceite ?></div>
                    </td>
                    <td>
                        <div class="titulo">Data de Processamento</div>
                        <div class="conteudo"><?php echo $data_processamento ?></div>
                    </td>
                    <td>
                        <div class="titulo">Valor do Documento</div>
                        <div class="conteudo lft"><?php echo $valor_documento ?></div>
                    </td>
                </tr>
                <tr>
                    <td colspan="7" class="noleftborder norightborder rtl">
                        <table width="40%" align="right">
                            <tr>
                                <td align="center" class="nopadding">
                                    <h3 style="font-weight:normal;font: 9px Arial;">Autenticação Mecânica</h3>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
        <br>
        <div class="linha-pontilhada">Corte na linha pontilhada</div>
        <br>
        <!-- Ficha de compensação -->
        <?php include('partials/layout-ficha-de-compensacao.phtml') ?>
    </div>
</body>
</html>
